### ISSUE TITLE
NullRef exception with vorto property when values = null

### ISSUE THREAD

**Issue by giuunit** [Jumoo/uSyncMigrations#129]
Not sure if this is a bug in uSyncMigrations or just a weird behaviour from uSync in our v7 build. 

We are attempting a migration from v7 to v11 with a solution using vorto initially. 

I have a doc type using vorto for a few plain text properties. Some properties have values:null when looking at the content that was generated by uSync. Example here: 

`  <type><![CDATA[{"values":null,"dtdGuid":"7cdf9aa2-89d5-4157-ac84-5dd9935a9e71"}]]></type>
`

When we run the process, we get the following exception: 

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at uSync.Migrations.Handlers.Shared.SharedContentBaseHandler`1.GetVariedValueNode(ISyncVariationPropertyMigrator migrator, String contentTypeAlias, String propertyName, SyncMigrationContentProperty migrationProperty, SyncMigrationContext context)

   at uSync.Migrations.Handlers.Shared.SharedContentBaseHandler`1.ConvertPropertyValue(String itemType, String contentType, XElement property, SyncMigrationContext context)

   at uSync.Migrations.Handlers.Shared.SharedContentBaseHandler`1.MigrateFile(XElement source, Int32 level, SyncMigrationContext context)

   at uSync.Migrations.Handlers.MigrationHandlerBase`1.MigrateFolder(String folder, Int32 level, SyncMigrationContext context)
```

I suspect the issue comes from that line: https://github.com/Jumoo/uSyncMigrations/blob/491ddeeb64a8442f18b824e4046e96ff6860b85f/uSync.Migrations/Handlers/Shared/SharedContentBaseHandler.cs#LL176C58-L176C64 as there's no null check for the Values property. 

If I replace the content of the property by an empty xml node: <type></type> then the process works fine for this file, but then I have the same issue with other files. I am wondering if I should manually clean them up or if it's an issue with uSync.Migrations.

**Comment by KevinJump** [comment]
Yes - looks like a missing null check that one, !

**Comment by giuunit** [comment]
I'll see if I can send a PR today
