### ISSUE TITLE
NestedContent Migrator: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by tkjaergaard** [Jumoo/uSyncMigrations#61]
I've made a export from a Umbraco V7 project and tries to import it into a V10 project and i get this error:

```
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at uSync.Migrations.Migrators.NestedContentMigrator.GetConfigValues(SyncMigrationDataTypeProperty dataTypeProperty, SyncMigrationContext context)
   at uSync.Migrations.Handlers.DataTypeMigrationHandler.MigrateFile(XElement source, Int32 level, SyncMigrationContext context)
   at uSync.Migrations.Handlers.MigrationHandlerBase`1.MigrateFolder(String folder, Int32 level, SyncMigrationContext context)
   at uSync.Migrations.Handlers.MigrationHandlerBase`1.MigrateFolder(String folder, Int32 level, SyncMigrationContext context)
   at uSync.Migrations.Handlers.MigrationHandlerBase`1.DoMigration(SyncMigrationContext context)
   at uSync.Migrations.Services.SyncMigrationService.MigrateFromDisk(Guid migrationId, String sourceRoot, SyncMigrationContext migrationContext, IOrderedEnumerable`1 handlers)
   at uSync.Migrations.Services.SyncMigrationService.MigrateFiles(MigrationOptions options)
   at lambda_method921(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted
```

I'm not sure of which file is causing it and why.

Let me know if you need more details 🙂

**Comment by tkjaergaard** [comment]
Found that this causes the issue 🙂 

```
<?xml version="1.0" encoding="utf-8"?>
<DataType Name="Privat Produkt - Moduler - Nested Content" Key="8fa2f969-fc9b-4c02-8c22-83147ab5a278" Id="Umbraco.NestedContent" DatabaseType="Ntext">
  <PreValues>
    <PreValue SortOrder="1" Alias="0"><![CDATA[[
  {
    "ncAlias": "hero",
    "ncTabAlias": "Hero",
    "nameTemplate": ""
  },
  {
    "ncAlias": "artikel",
    "ncTabAlias": "Artikel",
    "nameTemplate": ""
  },
  {
    "ncAlias": "privateProduktArtikelMFilLink",
    "ncTabAlias": "Artikel med fil",
    "nameTemplate": ""
  },
  {
    "ncAlias": "faq",
    "ncTabAlias": "FAQ",
    "nameTemplate": ""
  }
]]]></PreValue>
    <PreValue SortOrder="2" Alias="1"><![CDATA[[
  {
    "ncAlias": "hero",
    "ncTabAlias": "Hero",
    "nameTemplate": ""
  },
  {
    "ncAlias": "artikel",
    "ncTabAlias": "Artikel",
    "nameTemplate": ""
  },
  {
    "ncAlias": "privateProduktArtikelMFilLink",
    "ncTabAlias": "Artikel med fil",
    "nameTemplate": ""
  },
  {
    "ncAlias": "faq",
    "ncTabAlias": "FAQ",
    "nameTemplate": ""
  }
]]]></PreValue>
    <PreValue SortOrder="3" Alias="10"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="4" Alias="11"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="5" Alias="2"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="6" Alias="3"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="7" Alias="4"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="8" Alias="5"><![CDATA[0]]></PreValue>
    <PreValue SortOrder="9" Alias="6"><![CDATA[1]]></PreValue>
    <PreValue SortOrder="10" Alias="7"><![CDATA[1]]></PreValue>
    <PreValue SortOrder="11" Alias="8"><![CDATA[1]]></PreValue>
    <PreValue SortOrder="12" Alias="9"><![CDATA[1]]></PreValue>
  </PreValues>
</DataType>
```

**Comment by soreng** [comment]
hi @tkjaergaard 

I think you are getting the same error as me. What I encountered was that a property was missing a value, resulting in a call to 
`.ToString()` on the null value.

You can see fix here https://github.com/Jumoo/uSyncMigrations/pull/65 and maybe do a custom build of the PR, to verify if it fixes your error to.

**Comment by KevinJump** [comment]
Yeah i think #65 fixed this, and I've finally released it (in beta010)
