### ISSUE TITLE
cmsPropertyTypeGroup duplicate id issue

### ISSUE THREAD

**Issue by wardlawj** [Jumoo/uSyncMigrations#89]
Been trying out Usync Migrations this week to take a v7 site to v10 and it's been great but I've hit an issue with trying to migrate the the v7 content types.

I think the issue is with duplicate tab names, the way they've been setup in v7 means there's loads of content types with a tab called "Content" when I run the import the first content type with that name gets inserted into the cmsPropertyTypeGroup table but subsquent ContentTypes on the import with tabs called "Content" reuse the guid which then causes primary key violation errors. 

Here's an example of the error:

Cannot insert duplicate key row in object 'dbo.cmsPropertyTypeGroup' with unique index 'IX_cmsPropertyTypeGroupUniqueID'. The duplicate key value is (8f43317b-8530-3639-b95c-87f38a42cc29).

The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()

   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)

   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()

   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)

   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)

   at NPoco.Database.InsertAsyncImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco, Boolean sync)

   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)

   at NPoco.Database.Insert[T](T poco)

   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase`1.PersistNewBaseContentType(IContentTypeComposition entity)

   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.PersistNewItem(IContentType entity)

   at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy`2.Create(TEntity entity, Action`1 persistNew)

   at Umbraco.Cms.Core.Services.ContentTypeServiceBase`2.Save(TItem item, Int32 userId)

   at uSync.Core.Serialization.Serializers.ContentTypeBaseSerializer`1.SaveItem(TObject item)

   at uSync.Core.Serialization.SyncSerializerRoot`1.Deserialize(XElement node, SyncSerializerOptions options)

   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options)`
   
   Any help on a workaround/fix for this would be massivly appriciated.
   
   Thanks

**Comment by markadrake** [comment]
@wardlawj I've run into this same issue. Thanks for reporting it. I have a few other errors in my logs, but this one repeatedly appears. 

To test your hypothesis, I took a problematic document type (did not show up after import) and changed the tab names to "Content for xxx," (so all tab names became unique). After another import, the document type was available! 

_Obviously, this is not a fix — nobody wants to do this across 179 files._

**Comment by markadrake** [comment]
Does this issue relate to "Tabs sometimes don't have GUID's" (#86)?

If I'm following along with your code, the `alias` is being used to create a GUID. However, the `alias` here is not the `alias` of the content type. [It appears to be set to the value of the caption](https://github.com/snappercrumpleddog/uSyncMigrations/blob/d07a75e75d34d4960e25c5e1cc581261b3ca4783/uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs#L64).

cc @snappercrumpleddog

**Comment by markadrake** [comment]
Does this issue relate to "Tabs sometimes don't have GUID's" (#86)?

If I'm following along with your code, the `alias` is being used to create a GUID. However, the `alias` here is not the `alias` of the content type. [It appears to be set to the value of the caption](https://github.com/snappercrumpleddog/uSyncMigrations/blob/d07a75e75d34d4960e25c5e1cc581261b3ca4783/uSync.Migrations/Handlers/Seven/ContentTypeBaseMigrationHandler.cs#L64).

cc @snappercrumpleddog

**Comment by snappercrumpleddog** [comment]
If memory serves, v7 tabs don't have a concept of alias so one has to be created using the data to hand and in this case it's the caption.  A temp fix would be to replace alias.ToGuid() with a Guid.NewGuid() on line 82, but this might have a detrimental affect on uSync performance (however it should work!).  A better fix would be to use perhaps the doc type name and the tab alias combined with ToGuid as this should ensure the the guids don't get reproduced.  I'll try and test and fix when I get a moment, but if you beat me to it then please do put in a PR!

**Comment by KevinJump** [comment]
Yes - that is what the #90 is doing (i think if i understand what you are saying) - it is creating a new key based on doctype and tab alias. (so it should be unique across the site.)
